### ISSUE TITLE
Your organization's name

### ISSUE THREAD

**Issue by mpfilbin** [brightfame/brightfame#1]
Hello, I am wondering if you would be open to considering relinquishing ownership of the BrightFame organization within GitHub. I work for a small startup organization that also goes by that name. We are working to release our first product and would like to use the BrightFame name to house some of our public and private repositories. I noticed that there really hasn't been any activity under this account since 2009, so I am hopeful that you might at least be open to a conversation. Sorry for having to open an issue to communicate this with you, but I didn't see any other way to communicate. Thank you for time.

Sincerely,
Mike Filbin

**Comment by brightfame** [comment]
Sorry Mike, we will release something at some point!
